# Generated by Django 4.1.2 on 2022-10-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choise_text',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='wuestion_text',
            new_name='question_text',
        ),
    ]
